docs/AboutUs.md
Update Zheng Long's details in aboutUs page
=> Update Zheng Long's details in aboutUs page

.github/workflows/docs.yml
=> Update site-wide settings

README.md
Update remaining contents of the README.md
=> Update remaining contents of the README.md

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- Update user guide for add command
- Update help meesage for user when add command fails
-  Fix bug where Person was initilized with null medical report
- Update edit command parser to handle nric and birthdate fields
- Update definition of isSamePerson to be same NRIC
- Update relevant testss
=> Fix person command inconsistencies

docs/UserGuide.md
Update User Guide to include add, delete, and clear appointment commands
=> Update User Guide to include add, delete, and clear appointment commands

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/DeleteMedicalReportCommand.java
Update command word for delete medical report
=> Update command word for delete medical report

docs/UserGuide.md, src/main/java/seedu/address/ui/HelpWindow.java
Edit the user guide to align with the current program.
=> User guide edit

src/main/java/seedu/address/logic/commands/DeleteMedicineUsageCommand.java, src/main/java/seedu/address/logic/parser/DeleteMedicineUsageCommandParser.java, src/main/java/seedu/address/logic/parser/KlinixParser.java, src/main/java/seedu/address/model/Klinix.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/DeleteMedicineUsageCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteMedicineUsageCommandParserTest.java
Things to note:
- Delete medicine usage format: `deletemu [INDEX] ic/[NRIC]`
- Index is relative to what's displayed to the user
Things to check:
- try `deletemu ` to see if it returns the correct error message
- try other errors such as invalid index, invalid nric, see if errors get displayed correctly
resolves #40
=> Add Delete Medicine Usage Command

src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java, src/main/java/seedu/address/logic/parser/KlinixParser.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
Things to note:
Delete appointment format: deleteappt [INDEX] ic/[NRIC]
Index is relative to what's displayed to the user
Things to check:
try deleteappt to see if it returns the correct error message
try other errors such as invalid index, invalid nric, see if errors get displayed correctly
resolves https://github.com/AY2425S2-CS2103T-T09-2/tp/issues/50
=> Implement Delete Appointment Command

src/main/resources/view/AppointmentCard.fxml
Fix text descriptors in appointments
=> fix appointment text

src/main/java/seedu/address/logic/CommandHistory.java, src/main/java/seedu/address/logic/ICommandHistory.java, src/main/java/seedu/address/ui/CommandBox.java, src/test/java/seedu/address/logic/CommandHistoryTest.java, src/test/java/seedu/address/model/appointment/AppointmentListTest.java
- Similar functionality to command line, can use up down arrow to browse history
- Limitation as of now is that the command line history is not preserved across sessions
- Future enhancement is to save the command line history to storage
=> Implement command history functionality

src/main/java/seedu/address/logic/commands/MarkAppointmentVisitedCommand.java, src/main/java/seedu/address/logic/commands/UnmarkAppointmentVisitedCommand.java, src/main/java/seedu/address/logic/parser/KlinixParser.java, src/main/java/seedu/address/logic/parser/MarkAppointmentVisitedCommandParser.java, src/main/java/seedu/address/logic/parser/UnmarkAppointmentVisitedCommandParser.java, src/main/java/seedu/address/model/Klinix.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/appointment/Appointment.java, src/main/java/seedu/address/storage/JsonAdaptedAppointment.java, src/main/java/seedu/address/ui/AppointmentCard.java, src/main/resources/view/AppointmentCard.fxml, src/main/resources/view/MainWindow.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/storage/JsonAdaptedAppointmentTest.java
Add functionality to mark and unmark visited status in an appointment.
To mark an appointment: `markappt [index] ic/[nric]`
To unmark an appointment: `unmarkappt [index] ic/[nric]`
=> Add functionality to mark and unmark visited

src/main/java/seedu/address/model/Klinix.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/appointment/AppointmentList.java, src/main/java/seedu/address/model/appointment/AppointmentListByDate.java
=> Fix marking unmarking appointment shift order

src/main/java/seedu/address/model/Klinix.java
Fix Appointment Panel does not reflect existing appointments with matching date
Fix #129
=> Fix Appointment Panel does not reflect existing appointments with matching date

src/main/java/seedu/address/commons/util/AppointmentConflictFormatter.java, src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/appointment/AppointmentList.java, src/main/java/seedu/address/model/appointment/AppointmentListByDate.java, src/main/java/seedu/address/model/appointment/exceptions/OverlappingAppointmentException.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java, src/test/java/seedu/address/model/appointment/AppointmentListTest.java, src/test/java/seedu/address/ui/TestPersonListPanel.java
Add exceptions and tests for appointments overlapping 
Resolve #135 
Resolve #92
=> Add exceptions and tests for appointments overlapping 

src/main/java/seedu/address/commons/util/DateUtil.java, src/main/java/seedu/address/logic/parser/AddMedicineUsageCommandParser.java, src/main/java/seedu/address/logic/parser/ViewAppointmentByDateParser.java, src/test/java/seedu/address/logic/parser/AddMedicineUsageCommandParserTest.java
Fix issue where inputs in various commands can be set to an invalid date (Feb 31st)
Resolves #140 #141 #144
=> Fix issue where inputs in various commands can be set to an invalid date

src/main/java/seedu/address/model/person/BirthDate.java
Fix issue where birthday can be set to a date in the future
=> Fix issue where birthday can be set to a date in the future

src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/appointment/Appointment.java
Improve parsing for AddAppointmentCommandParser
=> Improve parsing for AddAppointmentCommandParser

docs/DeveloperGuide.md, docs/diagrams/UiClassDiagram.puml
Update UI diagram to include AppointmentCard and AppointmentListPanel
=> Update UI diagram to include AppointmentCard and AppointmentListPanel

docs/diagrams/AddAppointmentSequenceDiagram.puml
Fix diagram error for AddAppointmentCommand
=> Fix diagram error for AddAppointmentCommand

src/main/java/seedu/address/logic/parser/AddMedicineUsageCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/medicineusage/Dosage.java, src/main/java/seedu/address/model/medicineusage/MedicineName.java, src/main/java/seedu/address/model/medicineusage/MedicineUsage.java, src/main/java/seedu/address/model/person/MedicineUsageContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/storage/JsonAdaptedMedicineUsage.java, src/test/java/seedu/address/logic/commands/AddMedicineUsageCommandTest.java, src/test/java/seedu/address/logic/commands/ClearMedicineUsageCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteMedicineUsageCommandTest.java, src/test/java/seedu/address/logic/parser/AddMedicineUsageCommandParserTest.java, src/test/java/seedu/address/logic/parser/KlinixParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/medicineusage/MedicineUsageListTest.java, src/test/java/seedu/address/model/medicineusage/MedicineUsageTest.java, src/test/java/seedu/address/model/person/MedicineUsageContainsKeywordsPredicateTest.java, src/test/java/seedu/address/storage/JsonAdaptedMedicineUsageTest.java, src/test/java/seedu/address/ui/TestPersonListPanel.java
Things to note:
- MedicineName and Dosage are similar to Name class in Person
- They are added for better control valid input for medicine name and dosage
- The valid check currently is simple (only check if contain valid chars), can enforce char limit if needed
Things to check:
- Check comment headers
- Check parser logic
Things that have not been fixed (for future PRs):
- endDate can be before startDate
- endDate and startDate are parsed at low-level without using Util
=> Add MedicineName and Dosage class

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java, src/main/java/seedu/address/logic/commands/AddMedicineUsageCommand.java, src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java, src/main/java/seedu/address/logic/commands/ClearMedicineUsageCommand.java, src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DeleteMedicalReportCommand.java, src/main/java/seedu/address/logic/commands/DeleteMedicineUsageCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/FindMedicineUsageCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/commands/FindMedicineUsageCommandTest.java
- Replace person with patient
- Handle singular/plural cases
=> Improve appointment clearing message

src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/main/resources/view/ConfirmWindow.css, src/main/resources/view/MainWindow.fxml
=> Fix Ui inconsistencies

docs/UserGuide.md
Update UserGuide.md on parameter table
=> Update UserGuide.md on parameter table

docs/DeveloperGuide.md, src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java, src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
Update DeveloperGuide.md for manual testing for Appointment commands
=> Update DeveloperGuide.md for manual testing for Appointment commands

docs/DeveloperGuide.md
=> Fix use cases

docs/DeveloperGuide.md
Update dg manual testing for medicalreport
=> Update dg manual testing for medicalreport

docs/diagrams/DeleteSequenceDiagram.puml
=> Update parser diagram

src/main/java/seedu/address/commons/util/AppointmentConflictFormatter.java, src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/commands/AddMedicineUsageCommand.java, src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/appointment/Appointment.java, src/main/java/seedu/address/model/appointment/AppointmentListByDate.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedAppointment.java, src/main/java/seedu/address/ui/AppointmentCard.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/model/appointment/AppointmentTest.java
=> Update Appointment commands

docs/DeveloperGuide.md, docs/UserGuide.md
Refactor use case extensions for patient management and add edit patient use case
=> Refactor use case extensions for patient management and add edit patient use case

src/main/java/seedu/address/model/util/SampleDataUtil.java
This fixes the issue where `appton` command does not work properly when Klinix is first populated with sample data
=> Add appointments to sample data in SampleDataUtil

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
=> Fix AddAppoinmentCommand bug

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/Klinix.java, src/main/java/seedu/address/ui/PersonListPanel.java
Refactor appointment handling in EditCommand and Klinix classes
=> Fix editing person not updating in appointment list 

src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java, src/main/java/seedu/address/logic/commands/ClearMedicineUsageCommand.java, src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DeleteMedicalReportCommand.java
=> Fix output messages

src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/test/java/seedu/address/model/person/NameTest.java
=> Refine regex

docs/UserGuide.md, src/main/java/seedu/address/model/person/Name.java, src/test/java/seedu/address/model/person/NameTest.java
Update UserGuide.md and fix Name constraints
=> Update UserGuide.md and fix Name constraints

docs/DeveloperGuide.md
Update links to diagrams in DeveloperGuide.md and add new sections
=> Update links to diagrams in DeveloperGuide.md and add new sections

src/main/java/seedu/address/ui/AppointmentCard.java, src/main/resources/view/ConfirmWindow.css, src/main/resources/view/DarkTheme.css, src/main/resources/view/Extensions.css, src/main/resources/view/HelpWindow.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml, src/main/resources/view/ResultDisplay.fxml
=> Refactor CSS styles for improved dark theme consistency and button aesthetics

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/appointment/AppointmentList.java, src/main/java/seedu/address/model/person/MedicalReport.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/ui/TestPersonListPanel.java
Fix bug for Appointments and Medical Usage list being shared among all newly created Person.
=> Fix bug for Appointments and Medical Usage list being shared 

src/main/java/seedu/address/ui/AppointmentCard.java, src/main/resources/view/ConfirmWindow.css, src/main/resources/view/DarkTheme.css, src/main/resources/view/Extensions.css, src/main/resources/view/HelpWindow.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml, src/main/resources/view/ResultDisplay.fxml
Reverts AY2425S2-CS2103T-T09-2/tp#222
=> Revert "Refactor CSS styles for improved dark theme consistency and button aesthetics"

src/main/java/seedu/address/logic/Messages.java
=> Fix add message

src/main/java/seedu/address/logic/commands/UnmarkAppointmentVisitedCommand.java
Add index out of bounds message to UnmarkAppointmentVisitedCommand
Resolves #263
=> Add index out of bounds message to UnmarkAppointmentVisitedCommand

src/main/java/seedu/address/ui/CommandBox.java
Catch all exceptions in CommandBox to improve error handling
Resolves #238
=> Catch all exceptions in CommandBox to improve error handling

src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/ResultDisplay.java
Mainly added a mouse listener event that refreshes the display if the selected person's details are not present in the display
=> Add mouse click event to update result display in PersonListPanel

docs/UserGuide.md, src/main/java/seedu/address/commons/util/DateUtil.java
Update UserGuide.md and fix spacing in date error message
=> Update UserGuide.md and fix spacing in date error message

docs/DeveloperGuide.md, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/ClearAppointmentsCommand.java, src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/commands/DeleteMedicineUsageCommand.java
Update DeveloperGuide.md and update messages
=> Update DeveloperGuide.md and update messages

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java
=> Update duplicate person messages for clarity

docs/UserGuide.md
This pull request includes several updates to the `docs/UserGuide.md` file to improve clarity and consistency. The most important changes involve capitalization adjustments, additional clarifications, and enhanced instructions.
* Updated capitalization for terms like "Patient" in various sections to maintain consistency. [[1]](diffhunk://#diff-b50feaf9240709b6b02fb9584696b012c2a69feeba89e409952cc2f401f373fbL32-R48) [[2]](diffhunk://#diff-b50feaf9240709b6b02fb9584696b012c2a69feeba89e409952cc2f401f373fbL255-R256) [[3]](diffhunk://#diff-b50feaf9240709b6b02fb9584696b012c2a69feeba89e409952cc2f401f373fbL345-R357) [[4]](diffhunk://#diff-b50feaf9240709b6b02fb9584696b012c2a69feeba89e409952cc2f401f373fbL396-R399) [[5]](diffhunk://#diff-b50feaf9240709b6b02fb9584696b012c2a69feeba89e409952cc2f401f373fb …
=> Update patient details image format in User Guide

docs/index.md, src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java, src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java, src/test/java/seedu/address/model/appointment/AppointmentListTest.java, src/test/java/seedu/address/model/appointment/AppointmentTest.java, src/test/java/seedu/address/storage/JsonAdaptedAppointmentTest.java
=> Cite code usage

README.md, docs/site.json
=> Update product name to Klinix

docs/DeveloperGuide.md
Add Klinix logo to DeveloperGuide.md
=> Add Klinix logo to DeveloperGuide.md

docs/DeveloperGuide.md
Update link for diagrams for DeveloperGuide.md
=> Update link for diagrams for DeveloperGuide.md

docs/DeveloperGuide.md
=> Fix typo in DeveloperGuide.md
